Q.1(a)

In [1]:
import numpy as np
arr= np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


Q.1(b)

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]


In [3]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.ravel())

[1 2 3 2 4 5 1 2 3]


Q.1(c)

In [4]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(arr1 == arr2)


[[ True  True]
 [ True  True]]


Q.1(d)

In [5]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(x == most_frequent_value)[0]
print("Most frequent value in x:", most_frequent_value)
print("Indices:", indices)

Most frequent value in x: 1
Indices: [0 5 7 8 9]


In [6]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
indices = np.where(y == most_frequent_value)[0]
print("Most frequent value in y:", most_frequent_value)
print("Indices:", indices)

Most frequent value in y: 1
Indices: [0 1 2]


Q.1(e)

In [7]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')


In [8]:
total_sum = gfg.sum()
print("Sum of all elements:", total_sum)

Sum of all elements: 45


In [9]:
row_wise_sum = gfg.sum(axis=1)
print("Row-wise sum:\n", row_wise_sum)

Row-wise sum:
 [[14]
 [16]
 [15]]


In [10]:
col_wise_sum = gfg.sum(axis=0)
print("Column-wise sum:\n", col_wise_sum)

Column-wise sum:
 [[20  9 16]]


Q.1(f)

In [11]:
import numpy as np
n_array = np.array([[55, 25, 15],
                    [30, 44, 2],
                    [11, 45, 77]])


In [12]:
diagonal_sum = np.trace(n_array)
print("Sum of diagonal elements:", diagonal_sum)

Sum of diagonal elements: 176


In [14]:
eigenvalues = np.linalg.eigvals(n_array)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [98.16835147 28.097044   49.73460452]


In [15]:
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors:", eigenvectors)

Eigenvectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [16]:
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse_matrix)


Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [17]:
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)

Determinant of matrix: 137180.0000000001


In [18]:
import numpy as np
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product = np.matmul(p, q)
print("Matrix Multiplication:\n", product)

Matrix Multiplication:
 [[16 19]
 [26 31]]


In [19]:
cov = np.cov(p.flatten(), q.flatten())
print("Covariance matrix:\n", cov)

Covariance matrix:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [20]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product = np.matmul(p, q)
print("Matrix Multiplication:\n", product)
cov = np.cov(p.flatten(), q.flatten())
print("Covariance matrix:\n", cov)

Matrix Multiplication:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


Q.1(h)

In [21]:
import numpy as np
x = np.array([[2, 3, 4],
              [3, 2, 9]])
y = np.array([[1, 5, 0],
              [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner Product:\n", inner_product)
outer_product = np.outer(x, y)
print("Outer Product:\n", outer_product)
from itertools import product
cartesian_product = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian Product:\n", cartesian_product)

Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q.2(a)

In [22]:
import numpy as np
array = np.array([[1, -2, 3],
                  [-4, 5, -6]])
abs_array = np.abs(array)
print("Absolute Value:\n", abs_array)
flat = array.flatten()
p_flat = np.percentile(flat, [25, 50, 75])
print("Percentiles of flattened array (25th, 50th, 75th):", p_flat)
p_col = np.percentile(array, [25, 50, 75], axis=0)
print("Percentiles for each column (rows 25th, 50th, 75th):\n", p_col)
p_row = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles for each row (rows 25th, 50th, 75th):\n", p_row)


Absolute Value:
 [[1 2 3]
 [4 5 6]]
Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]
Percentiles for each column (rows 25th, 50th, 75th):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row (rows 25th, 50th, 75th):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [23]:
mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print("Flattened array - Mean:", mean_flat)
print("Flattened array - Median:", median_flat)
print("Flattened array - Std Dev:", std_flat)


Flattened array - Mean: -0.5
Flattened array - Median: -0.5
Flattened array - Std Dev: 3.8622100754188224


In [24]:
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Column-wise Mean:", mean_col)
print("Column-wise Median:", median_col)
print("Column-wise Std Dev:", std_col)

Column-wise Mean: [-1.5  1.5 -1.5]
Column-wise Median: [-1.5  1.5 -1.5]
Column-wise Std Dev: [2.5 3.5 4.5]


In [25]:
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Row-wise Mean:", mean_row)
print("Row-wise Median:", median_row)
print("Row-wise Std Dev:", std_row)


Row-wise Mean: [ 0.66666667 -1.66666667]
Row-wise Median: [ 1. -4.]
Row-wise Std Dev: [2.05480467 4.78423336]


In [26]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
np.floor(a)
np.ceil(a)
np.trunc(a)
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

Q.3(a)

In [27]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
np.sort(array)
np.argsort(array)
np.sort(array)[:4]
np.sort(array)[-5:]

array([ 16,  52,  54,  62, 453])

Q.3(b)

In [28]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
array[array % 1 == 0]
array[array % 1 != 0]

array([1.2, 2.2])

Q.4(a)